Issue 8/card bodega
frontendcafe/cmyk-blueberry pull request #15
Opened 2021-09-03 00:46 UTC by celcab27

## Descripcion
Se creó el componente CardStore para las cards de la página que contienen la información de las bodegas. 

La card recibe 3 propiedades:
isTransparent = Para elegirle un tema (si es true, la card tendrá un fondo transparente, si es true tendrá un color de fondo)
title = El título de la card
body = El texto de la card 

## Capturas de pantalla
![imagen](https://user-images.githubusercontent.com/63078654/131933606-079bb2c5-db12-4cbc-bfc0-63aff7c37167.png)
![imagen](https://user-images.githubusercontent.com/63078654/131933634-e33c25f0-9d34-4436-9111-410fca62bb53.png)
![imagen](https://user-images.githubusercontent.com/63078654/131933667-540fbf0a-aece-4ca7-820e-e6165baa6171.png)
![imagen](https://user-images.githubusercontent.com/63078654/131933695-acde113d-e7ec-4d16-9894-ae1b25fe42bf.png)

## Issue
https://github.com/frontendcafe/cmyk-blueberry/issues/8

2021-09-03 01:37 UTC, anaggithub requested changes

2021-09-03 01:37 UTC, anaggithub commented on src/components/CardStore/index.js
> +    console.log(isTransparent);
Holis! Te dejo algunas correciones! 

Generalmente no se envían console.logs a master, a no ser que sea un console.log(e) de un try catch.. 
Acá en la línea 6 colocaste un console.log de ayuda para ti imagino, esto no debería ir a master. Quedamos a la espera de que envíes un commit quitando este y otros console.logs si los hubiera.

2021-09-03 01:37 UTC, anaggithub commented on src/components/CardStore/styles.scss
> +
Acá hay muchas líneas en blanco, generalmente no se dejan líneas así vacíasss. Podríamos usar todos la extensión prettier para dar formato al código. MAñana voy a consultarlo en el canal a ver qué les parece!

2021-09-03 01:42 UTC, anaggithub requested changes

2021-09-03 01:42 UTC, anaggithub commented on src/components/CardStore/index.js
> +import "./styles.scss";
Holi! Veo que no has guardado el texto del componente en ningún lado. En la reunión mencionamos que los textos, en caso de ser largos los podríamos colocar en archivos .json. Esto no lo aclaré en el ticket porque di por sentado de que se iba a entender. Mala mía!

Imagino que pusiste el texto en algún lado porque veo que probaste el componente pasandole los datos por props y así tomaste las capturas.

En donde guardaste esos datos? Eso también hay que comitearlo. 
Podría ser un archivo data.js en la misma carpeta del componente, junto con el index y el styles.

Te muestro este ejemplo de otro proyecto:
![image](https://user-images.githubusercontent.com/47753872/131937903-3ca9e13b-d23f-469c-9ae0-0f6629ddd4c2.png)

2021-09-03 01:59 UTC, anaggithub commented
Están hermosas las cards!! Felicitacionesss ♡ ♥ ♡ ♥ ♡ ♥ ♡ ♥ ♡ ♥

2021-09-03 14:53 UTC, anaggithub commented
Holis!! Probé renderizar un par de cards en App y pareciera q me pone una arriba de otra, mostrandome la tercera, y las otras parecieran estar ocultas. En el dom sí están las tres, pero solo se ve la tercera. 
Queres revisarlo?
![image](https://user-images.githubusercontent.com/47753872/132025310-196c2f41-bebe-4f26-bdce-9c30aa86ca64.png)

2021-09-05 00:06 UTC, anaggithub commented
Holi! Te dejo algunos detalles de estilos!

Aca le podrias poner un poquito más de padding, para que no se suba al renglón más texto del que realmente le va.
![image](https://user-images.githubusercontent.com/47753872/132110792-82028d3e-066d-447d-b6a5-f86d8b2a675e.png)

Eso sería en una media queri para pantalla grande, en mobile está de 10.

Otra cosita que noto es que te olvidaste del corazoncito que está adentro de la casita..

![image](https://user-images.githubusercontent.com/47753872/132110833-e9e18e53-15db-4046-9536-ec02b8e3868e.png)

2021-09-06 22:09 UTC, Micaela2016 commented
Hola Cel, quedaron hermosas las tarjetas!! Me gusto la forma en que lo hiciste :)
Lo único que noto diferente fue que agregaste una carpeta dentro de assets, y que yo no lo hice. No estoy muy segura si habría conflicto en eso, de todas formas no tengo problema en modificarlo así es consistente.
Estaba esperando los cambios de esos detalles que te dijo Hadita, ahora si se me ve el corazoncito!
En mi pantalla no tenia el problema del padding antes del arreglo, pero quizás en alguna mas grande si.

2021-09-06 22:10 UTC, Micaela2016 approved these changes

2021-09-07 16:18 UTC, anaggithub approved these changes

2021-09-07 16:20 UTC, Micaela2016 approved these changes

2021-09-07 16:23 UTC, merged