Issue 10/información cards desktop
frontendcafe/cmyk-blueberry pull request #16
Opened 2021-09-05 19:42 UTC by erianvc

## Descripcion
- [x] Se creó las card para desktop de la sección de información

## Capturas de pantalla

### Card primary
![image](https://user-images.githubusercontent.com/4275190/132139339-dfbc049a-04a1-4296-b0a0-cf8d8399daed.png)

### Card secondary
![image](https://user-images.githubusercontent.com/4275190/132139367-b3e8d1a9-7010-40dc-9e57-401a4aa31ea4.png)

## Issue
[Crear cards desktop de la sección de información #10](https://github.com/frontendcafe/cmyk-blueberry/issues/10)

2021-09-06 14:12 UTC, anaggithub commented
Hola Eri! No sé si recuerdas que habíamos decidido colocar las imágenes en una carpeta Assets. Quizás lo hablamos la última reunión justo antes de que lleguess, la verdad no recuerdoo. En ese caso se nos pasó decirtelo, mil disculpas por eso.

Podrías moverlas a dicha carpeta.
Leo en su PR ya la creó, justo dentro de src, pero claro aún no lo mergeamos.
https://github.com/frontendcafe/cmyk-blueberry/pull/17/files

2021-09-06 14:46 UTC, anaggithub requested changes

2021-09-06 14:46 UTC, anaggithub commented on src/App.js
> +      <section style={{
Holis! La tarea de las cards aún no incluía la sección de información, esa la trabajarás en la próxima issue!! Podrías quitar esta parte por ahora y dejar limpio App.js?

Recuerden que tenemos que tratar de no commitear cambios en archivos donde aún no se nos ha pedido trabajar :)

2021-09-06 21:52 UTC, LeoCoronel commented on src/App.js
> +          Ubicada en Mendoza, Bodegas Wineberry se encuentra en un mágico lugar.
Yo ya realice el data.js así no hay que escribir todo el texto de las cards cuando se realice el merge habría que cambiar el texto recibido

2021-09-07 15:36 UTC, anaggithub approved these changes

2021-09-07 17:39 UTC, LeoCoronel approved these changes

2021-09-07 19:22 UTC, merged