Issue 4/cards mobile informacion
frontendcafe/cmyk-blueberry pull request #17
Opened 2021-09-06 00:32 UTC by LeoCoronel

## Descripcion
Se trabajo en las cards de la sección información para la versión mobile, en el cual el componente Card recibe por props los textos e imagenes.

## Capturas de pantalla
![image](https://user-images.githubusercontent.com/36435141/132145780-704842ae-93eb-4bdb-9137-56995c1be53e.png)
![image](https://user-images.githubusercontent.com/36435141/132145794-dec8dc81-dd5e-4555-972c-7cf864348fbf.png)

## Issue
Issue https://github.com/frontendcafe/cmyk-blueberry/issues/4

2021-09-06 14:16 UTC, anaggithub requested changes

2021-09-06 14:16 UTC, anaggithub commented on src/App.js
> +      {cards.map((card) => {
Holis! Podrías quitar esto? Entiendo que lo usaste para probar tus cards, pero en realidad las cards no irían así en App.js, si no que irían dentro de una sección que aún no se comenzó a trabajar! 

Tranki que los demás también lo hicieron, pero la idea es tratar de hacerlo como se hace en un equipo real :D

2021-09-06 15:19 UTC, LeoCoronel commented on src/App.js
> +      {cards.map((card) => {
Listo, ya deje como estaba, gracias por el aviso

2021-09-07 14:05 UTC, erianvc commented on src/components/Cards-mobile/index.js
> +import React, { useState } from 'react';
Se debería utilizar CamelCase para el nombre de carpetas de componentes, quedando como **CardsMobile**

2021-09-07 20:09 UTC, anaggithub approved these changes

2021-09-07 20:44 UTC, erianvc approved these changes

2021-09-07 20:44 UTC, merged