Issue 1/navbar
frontendcafe/cmyk-blueberry pull request #18
Opened 2021-09-06 14:31 UTC by Micaela2016

## Descripción
Se creo el componente navbar, tanto de la vista mobile como desktop.
Aclaración: 
- Cada componente creado de una sección de la pagina, deberá contener un id. Por ejemplo, para la sección "nuestras bodegas" también llamada "bodegas wineberry" se deberá usar id="nuestrasBodegas".

## Capturas de pantalla
Menú en versión desktop: 
![image](https://user-images.githubusercontent.com/23745160/132230362-b26fa002-3ebb-4b8b-a835-198744b1c094.png)
![image](https://user-images.githubusercontent.com/23745160/132230616-6ec676d3-6a41-458a-b203-2c438fe33f8c.png)
![image](https://user-images.githubusercontent.com/23745160/132232248-b8faf5ec-cb04-41fb-b4d7-64d0fc4d6949.png)
![image](https://user-images.githubusercontent.com/23745160/132232324-a5d8c875-44fc-408f-8e1b-d3467d38923e.png)

Menú en versión mobile:
![image](https://user-images.githubusercontent.com/23745160/132230752-661d0536-cb14-4a80-97f5-35e02c939ae5.png)
![image](https://user-images.githubusercontent.com/23745160/132230841-ae72da41-fe8e-45fd-a7f4-9125565e1a8d.png)

## Issue
Issue trabajado: [#1 ](https://github.com/frontendcafe/cmyk-blueberry/issues/1)

2021-09-06 14:51 UTC, anaggithub requested changes

2021-09-06 14:51 UTC, anaggithub commented on src/App.js
> +      <Navbar/>
Holis!! Primero que nada! Qué hermoso te quedóoo!!!

Como pequeño cambiecito, te voy a pedir que limpies este App.js, ya que tu componente ya va sobre App.js (los demás PRS son sobre componentes sueltos y no una sección especifica en APP). Este componente tuyo sí va en App.

Entonces, la idea es que lo coloques donde va (arriba de todo) y las demás cosas que no van, las quitemos. Así que fletalas nomass porfi.

![image](https://user-images.githubusercontent.com/47753872/132234639-d86c2d13-e34b-4ba4-acc0-b825503caa8d.png)

Te animás?

2021-09-06 20:50 UTC, celcab27 approved these changes

2021-09-07 02:44 UTC, anaggithub commented
Encontré otra cosita!

![image](https://user-images.githubusercontent.com/47753872/132276207-925962d4-5e7f-432e-94fb-32c1307bbd1a.png)

2021-09-09 18:34 UTC, MarcosNASA commented on src/components/Navbar/index.js
> +    const [click, setClick] = useState(false);
¡Está genial! Enhorabuena.

Me gustaría comentar sólo un detalle: cuando definimos variables que contienen valores booleanos, es una buena práctica añadir al nombre un prefijo integorrativo. Por ejemplo:
```js
const isDisabled = false // ¿está deshabilitado? No
const hasAccess = true // ¿tiene acceso? Sí
const didChange = false // ¿cambió? No
```

Cuando las variables tienen estos nombres, es muy fácil identificar si son o no booleanos y, a la hora de usarlas en el código, éste se lee de forma más natural:
```js
if (isDisabled) {} // si tiene acceso...
if (hasAccess) {} // si tiene acceso...
if (didChange) {} // si cambió...
```

En este caso, te propongo como nombre `isOpen` (está abierto). De modo que la linea 26 quedaría:
```js
{isOpen && ( // si está abierto...
  ...
 )} 
```

2021-09-10 14:02 UTC, robbiesdream commented on src/components/Navbar/index.js
> +            <div className={isOpen ? "navbar__menu active" : "navbar__menu"}>
Aquí podrías utilizar `navbar__menu navbar__menu--active`

2021-09-10 14:02 UTC, robbiesdream commented on src/components/Navbar/index.js
> +                    <li className="navbar__menu-item hidden" onClick={closeMobileMenu}>
idem

2021-09-10 14:02 UTC, robbiesdream commented on src/components/Navbar/styles.scss
> +    }
En consideración del comentario referido a esta clase.
```scss
&__menu {
    // Aquí lo referido al estado normal
    &--active{
    // Aquí lo referido al estado active
    }
}
```

2021-09-10 14:18 UTC, MarcosNASA commented on src/components/Navbar/index.js
> +    const [isOpen, setClick] = useState(false);
Estaría bien, cuando se actualiza el nombre del estado, actualizar también el nombre de la state dispatcher function (el `setClick`) para que estén coordinados:
```suggestion
const [isOpen, setIsOpen] = useState(false);
```

2021-09-11 18:41 UTC, robbiesdream commented on src/components/Navbar/index.js
> +                    <img className="navbar__mobile--icon" alt="Icon cierre" src={closeIcon}/>
Estaba bien la implementación anterior.

_navbar__mobile-icon_ significa **el elemento _mobile icon_ del bloque _navbar_**
_navbar__mobile--icon_ significa **la version _icon_ del elemento _mobile_ del bloque _navbar_**

2021-09-11 18:41 UTC, robbiesdream commented on src/components/Navbar/index.js
> +                    <img className="navbar__mobile--icon" alt="Icon cierre" src={closeIcon}/>
Lo mismo va para todo el resto

2021-09-11 18:41 UTC, robbiesdream commented on src/components/Navbar/index.js
> +            <div className={isOpen ? "navbar__menu navbar__menu--active" : "navbar__menu"}>
Por las dudas, este caso esta bien:

_navbar__menu--active_ es **la version _active_ del elemento _menu_ del bloque _navbar_**

2021-09-11 18:50 UTC, gisellechaumont commented
Lo probe y funciona perfecto
![image](https://user-images.githubusercontent.com/69175205/132958308-f2b10919-488f-4f7f-9ddc-9741d96c94ef.png)
![image](https://user-images.githubusercontent.com/69175205/132958329-4668b3e1-c55b-4a89-8516-d42af9223066.png)
![image](https://user-images.githubusercontent.com/69175205/132958337-fe4ac7e1-1384-405f-aa4a-e6ee8c3061e9.png)

2021-09-11 19:23 UTC, anaggithub commented
Holis! Está quedando hermosoo. Solo dejo unas últimas cositas: 

- faltaria la sombrita debajo del navbar :
![image](https://user-images.githubusercontent.com/47753872/132959167-600c881d-fa7d-42fc-8cb1-7f7eda25c8a9.png)

- el bold del botón, el texto está menos gruesito que lo que se ve en el figma.
el tuyo se ve asi:
![image](https://user-images.githubusercontent.com/47753872/132959180-36c52b56-e575-4360-a743-4588a136d4c9.png)

y en el figma:
![image](https://user-images.githubusercontent.com/47753872/132959189-73a8f1c9-21c1-4baf-9cea-512228754cf3.png)

nos estaria faltando el font-weight: 700
![image](https://user-images.githubusercontent.com/47753872/132959203-747d64d5-6730-4082-9c17-031c72c4bab9.png)

Según chismie en el figma, todos los botones tienen ese weight, así que ese cambio lo podrías mandar al componente Button. Te animás?

2021-09-11 21:46 UTC, robbiesdream approved these changes

2021-09-12 17:15 UTC, anaggithub approved these changes

2021-09-12 17:15 UTC, merged