button listo
frontendcafe/cmyk-blueberry pull request #19
Opened 2021-09-06 23:26 UTC by gisellechaumont

## Descripcion
Se creo el componente button y se lo hizo reutilizable. A través de las props agrego variant y text. 
Se creo los estilos para cada variant. 
Se lo hizo responsive a través de media queries. 

## Capturas de pantalla
- Primary para desktop
![primary md](https://user-images.githubusercontent.com/69175205/132265379-22a3f35e-7756-45fc-bab0-71b4e2e42311.JPG)
- Primary para mobile
![primary sm](https://user-images.githubusercontent.com/69175205/132265373-c55471c9-ccbe-4827-bf8c-b33d4bf27b13.JPG)
- Secondary para desktop
![secondary md](https://user-images.githubusercontent.com/69175205/132265378-de63491f-093c-481c-beea-6aed2e1d4d64.JPG)
 -Secondary para mobile
![secondary sm](https://user-images.githubusercontent.com/69175205/132265372-c25a51db-1d59-4225-9fae-a96e619dbec9.JPG)
- Light (no encontré versión mobile)
![light](https://user-images.githubusercontent.com/69175205/132265377-40c3963b-3c11-46f2-9bb8-7c46d860e881.JPG)
- Light-lg (no encontré versión mobile)
![light-lg](https://user-images.githubusercontent.com/69175205/132265376-4f4a60da-e8b5-49fc-b524-bcfb2f9826b9.JPG)
- Blueborder desktop
![blueborder md](https://user-images.githubusercontent.com/69175205/132265375-2e9a3db2-1ec1-4b4b-9f54-166584a5c84e.JPG)
-Blueborder mobile
![blue border sm](https://user-images.githubusercontent.com/69175205/132265371-19da6bf7-9378-47ec-8de4-7f702adc3e66.JPG)
-Greenborder desktop
![greenborder](https://user-images.githubusercontent.com/69175205/132265374-74a33b9b-14c5-4e13-969e-0484309fe19b.JPG)
-Greenborder mobile
![greenrboder sm](https://user-images.githubusercontent.com/69175205/132265370-6b3a19bc-ccbe-4c42-a0a2-e05452ffe1dc.JPG)

## Issue
https://github.com/frontendcafe/cmyk-blueberry/issues/2

2021-09-07 00:33 UTC, anaggithub requested changes

2021-09-07 00:33 UTC, anaggithub commented on src/components/Button/styles.scss
> +right: 8.2%;
Holis! Primero que nada, felicitaciones!! Están hermososs los botoness!!! ♡♡♡

Como primera correción así rapidito, mañana veré con más tiempo el PR, veo que el código está indentado medio mal! Con respecto a esto hace poquito hablamos en el canal de usar todos la extensión Prettier en el vcode, la podes encontrar acá:
![image](https://user-images.githubusercontent.com/47753872/132268005-255124bd-731e-46d1-afbe-292f4d4981a5.png)

Luego de habilitarla en tu visual estudio, podés dar formato con ella a tus archivos, y lo que hará es indentarte el código de manera automática, también borrar espacios innecesarios, etc. 

:D

2021-09-07 16:04 UTC, celcab27 reviewed
Quizá para los tamaños estaría bueno usar los size de la sección utils. Entonces, en vez de poner font-size:20px capaz se puede poner font-size:$size-lg

2021-09-07 16:09 UTC, gisellechaumont commented
> Quizá para los tamaños estaría bueno usar los size de la sección utils. Entonces, en vez de poner font-size:20px capaz se puede poner font-size:$size-lg

Gracias Cel por la observacion! Es la primera vez que uso sass asiq se me ha pasado. Ahora lo modifico

2021-09-07 16:16 UTC, celcab27 commented on src/components/Button/styles.scss
> +  left: 103px;
No me terminan de quedar claro cuál sería la función de los atributos left, top, bottom, right acá! Por lo que tengo entendido, se usan más que nada para poscionar cuando el elemento tiene position absolute.

2021-09-07 16:18 UTC, celcab27 reviewed
En vez de manejar los estilos con id no sería mejor manejarlos con clases?? Porque puede haber más de un botón por componente.

2021-09-07 16:32 UTC, Micaela2016 commented on src/components/Button/styles.scss
> +  left: 103px;
Si, quizás esos estilos no harían falta! Probé sacarlos y no tienen ningún cambio en los botones

2021-09-07 19:27 UTC, gisellechaumont commented on src/components/Button/styles.scss
> +  left: 103px;
Gracias chicas 🥰

2021-09-07 20:49 UTC, celcab27 commented on src/components/Button/styles.scss
> +  font-size: 14.4601px;
Acá no se podría usar un $size-sm en vez de poner directamente los 14px??

2021-09-07 20:52 UTC, celcab27 commented on src/components/Button/styles.scss
> +  font-size: 14, 46px;
Acá estás poniendo dos valores dentro del font-size y me lo está tomando como inválido! Quizá estaría mejor reemplazarlo por $size-sm

2021-09-07 20:54 UTC, celcab27 commented on src/components/Button/styles.scss
> +  padding: 7px, 14px, 7px, 14px;
El navegador me está tomando esto como valor de propiedad inválido, probá sacándole las comas

2021-09-07 20:54 UTC, celcab27 commented on src/components/Button/styles.scss
> +    padding: 9px, 18px, 9px, 18px;
Acá también habría que sacar las comas creo

2021-09-07 20:57 UTC, celcab27 commented on src/components/Button/styles.scss
> +  padding: 10px, 20px, 10px, 20px;
Acá también está el problema de las comas!

2021-09-07 20:57 UTC, celcab27 commented on src/components/Button/styles.scss
> +  font-size: 16px;
Creo que se puede reemplazar por $base-size

2021-09-07 20:58 UTC, celcab27 commented on src/components/Button/styles.scss
> +  font-size: 16px;
Creo que se puede reemplazar por $base-size

2021-09-07 21:02 UTC, celcab27 commented on src/components/Button/styles.scss
> +  align-items: center;
Veo que los botones en general están bien centrados así que no sé que tanto sea un problema pero usaste el align-items: center en varias partes del código y el navegador me lo tira como inválido porque esta propiedad solo se puede usar sobre un contenedor flex! Creo que se solucionaría agregándole display:flex a la clase button

2021-09-07 22:54 UTC, anaggithub commented on src/components/Button/styles.scss
> +  padding: 6.2449px 12.4898px;
Holis! Te hago ua consulta! Son raros estos valores con decimales, son valores que tomaste del figma? No haría falta colocar decimales, es myu muy raro ver eso en un padding o en un width o height. Si son valores del figma hay que tomarlos con pinzass, solo tomar del figma lo que realmente necesitamos.

El boton debe ser flexible también, si le cambiamos su texto su ancho se debería adaptar al texto que tiene... Con este width fijo que le has colocado eso podrá ocurrir? 

Esto es algo super importante a tener en cuenta :)

2021-09-08 22:18 UTC, gisellechaumont commented on src/components/Button/styles.scss
> +  padding: 6.2449px 12.4898px;
Hola!!! Ya están resueltas ambas cosas!!! 🤗

2021-09-11 16:52 UTC, anaggithub approved these changes

2021-09-11 17:11 UTC, Micaela2016 approved these changes

2021-09-11 17:12 UTC, merged