Issue 3/main
frontendcafe/cmyk-blueberry pull request #22
Opened 2021-09-07 23:19 UTC by IgnacioCernich

## Descripcion
Se realizó el componente Main de la pagina mobile first, y desktop. Dejando espacio para la NavBar

## Capturas de pantalla
![pagmobile](https://user-images.githubusercontent.com/81936182/132422170-decf603a-5b9f-4b6d-9a85-f21bee1990eb.png)
![pagdesktop](https://user-images.githubusercontent.com/81936182/132422248-4a85785c-dc9f-4c8b-a5b6-38f2f3f3e15d.png)

## Issue
https://github.com/frontendcafe/cmyk-blueberry/issues/3

2021-09-08 17:01 UTC, nicolas-hernandezamor commented on src/components/Main/style.scss
> +      }
Se podrían juntar los elementos comunes en una sola clase y destacar las particularidades? Tal vez inclusive, podría ser una sóla imagen y manejar las diferencias con los mediaqueries?

2021-09-09 13:17 UTC, IgnacioCernich commented on src/components/Main/index.js
> +                    <img src={imagen} className = "imagen" alt="imagen de una copa de vino"/>
Necesité llamar a la imagen dos veces porque es una imagen cuadrada modificada con clip path para que superpuestas queden de la forma requerida

2021-09-09 17:29 UTC, robbiesdream commented on src/components/Main/index.js
> +                    <img src={imagen} className = "imagen" alt="imagen de una copa de vino"/>
y considerando que ese comportamiento se da en mobile/desktop, no podrías utilizar @media para diferir el clippath?

2021-09-09 18:44 UTC, LeoCoronel commented
Podrías cambiar los nombres de las clases para utilizar BEM

2021-09-09 18:54 UTC, IgnacioCernich commented on src/components/Main/index.js
> +                    <img src={imagen} className = "imagen" alt="imagen de una copa de vino"/>
En mobile le puse hidden a las imagenes porque ahi solo utilice un background de esa imagen, si es a lo que te referis

2021-09-10 23:26 UTC, LeoCoronel commented on src/components/Main/style.scss
> +  .texto-simple {
En BEM los guiones son dobles por lo tanto deberias utilizar -- o __

2021-09-10 23:30 UTC, LeoCoronel reviewed
Para usar BEM tenes que tener en cuenta los elementos y los modificadores y por ejemplo los textos que tenes que van a la derecha son modificadores por lo que deberia ser texto--derecha al igual que texto--cursiva y los demás, y los elementos como contenedores tambien deberias cambiar por ejemplo el img-container deberia ser img__container

2021-09-11 10:45 UTC, robbiesdream commented on src/components/Main/index.js
> +                        <span className = "texto__cursiva">
Esto es general para toda la aplicación de BEM:
En este caso tu bloque sería _texto_ y _alineado a la derecha_ es un _**modificador**_. 
Es una "forma de presentar" el bloque _texto_.

La forma final de la clase sería: 
`texto--alineado-derecha` (-- para modificador y el guión medio sólo separa las palabras)
`texto--cursiva`

Otro comentario es que los guiones, bajos o medios, solo deberían usarse dobles cuando se usan para definir un elemento o un modificador. De manera que si por ejemplo tuviesemos:

`menu__navigation-item` 
Tenemos un bloque _menu_ y un elemento _navigation-item_

`menu__navigation__item`
Tendríamos un elemento _item_ del elemento _navigation_ del bloque _menu_. Pero esto no es un buen uso del framework BEM.

2021-09-11 17:29 UTC, gisellechaumont commented
Lo probe en mi compu y la version mobile esta se ve bien pero la imagen no queda igual que el diseño de figma. 

![2334](https://user-images.githubusercontent.com/69175205/132956176-b4698257-5191-41e0-b246-0c585e785a88.JPG)

En desktop la imagen no se ve bien. 
![Captura12](https://user-images.githubusercontent.com/69175205/132956180-7ab5965a-6d7e-438d-8239-95d57f67579c.JPG)

2021-09-11 17:37 UTC, gisellechaumont reviewed
- Falta pasar a bem 
- Los numeros que tengan decimales hacerlos numeros enteros
- Se podria usar sass para --> visibility: visible

2021-09-11 21:47 UTC, robbiesdream commented
@IgnacioCernich Tenes conflictos en el PR

2021-09-12 17:51 UTC, anaggithub requested changes

2021-09-12 17:51 UTC, anaggithub commented on src/components/Main/index.js
> +            <div className = "container">
Holi!!! Primero que nada, felicitaciones por el trabajo. Viene muy muy bien!!! 

Acá te voy a dejar algunas correcciones para hacer y mejorarlo!
1) Tu sección la hemos llamado Main porque es la sección de la web donde están los datos más importantes de la misma, y de hecho para esta sección existe un tag de html `main` que deberías usar. En la línea 8 tu elemento contenedor de toda la sección deberia ser main, es decir:` <main className = "container">`.
Más info sobre el tag main: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main.

2) Con respecto al uso de BEM en tu componente, es un componente bastante sencillo, tiene un bloque main, que podríamos llamar main directamente en vez de container (esto es una sugerencia) y luego sus elementos deberían ser llamados con guiones bajos. El div que llamás "texto", es un elemento del bloque main, por lo tanto usariamos dos guiones bajos para el mismo.
Luego lo que llamas "simple", "alineado-derecha", son modificadores de ese texto, y esos los concatenamos con dos guiones.

Te dejo una captura de cómo podría ser si usáramos main en vez de container:

![image](https://user-images.githubusercontent.com/47753872/132997411-fb420a53-dca4-428d-b631-370a7560a09a.png)

Ojo que al hacer este cambio, vas a tener que actualizar el archivo de estilos usando ampersand. Ejemplos tomados de nuestro navbar:
![image](https://user-images.githubusercontent.com/47753872/132997490-381b206d-838e-4c8f-84c7-5aff83e382eb.png)

![image](https://user-images.githubusercontent.com/47753872/132997503-0a47977e-0705-46b4-8b8a-6561ff50d334.png)

2021-09-12 17:51 UTC, anaggithub commented on src/components/Main/index.js
> +                    <button>
Ya tenemos mergeado nuestro componente Button, el cual debes importar en Main y usarlo en esta sección. El mismo permite recibir el texto que va a tener, una variante que define sus estilos (en tu caso es la variante "primary" al menos en desktop) y luego si necesitas agregarle estilos, también puede recibir estilos por prop. Podés ver un ejemplo de cómo hacer todo esto en el componente Navbar, donde mica importó y utilizó el componente Button que crearon las chicas.

2021-09-12 17:54 UTC, anaggithub commented
Otra cosita, sería lo ideal que el componente sea responsive en todo momento y al agrandar y achicar la pantalla los elementos se acomoden sobre el espacio disponible.

Al achicar la pantalla tu componente deja de ser responsive:

![image](https://user-images.githubusercontent.com/47753872/132997673-e00e05ee-7f9f-41b4-8eb3-bd346ed98c8f.png)

Esto se puede resolver jugando con CSS, display flex, justify content, width 100%, etc. Ir probando que los elementos siempre estén dentro de su padre y se acomoden distribuidos en el espacio disponible.

Luego con media query uno define cosas especificas, por ej cambiar de una imagen a otra como hiciste, y q los elementos se adapten a ese cambio.

Pero la ubicación en su elemento padre, debería ser siempre responsive.

2021-09-14 22:54 UTC, nicolashernandezamor-drd commented on src/components/Main/index.js
> +          <span className="main__texto--texto-cursiva">
Tenes una repetición innecesaria acá.
main__texto--texto-cursiva -> main__texto--cursiva

2021-09-17 00:07 UTC, anaggithub approved these changes

2021-09-17 03:12 UTC, narvmtz commented
Cierro el PR para volver a hacer trigger del preview en netlify.

2021-09-17 18:58 UTC, gisellechaumont commented
Quedaron re bien los arreglos!! Comparto fotitos. 
Quedo super bien la foto nueva y el boton.

![image](https://user-images.githubusercontent.com/69175205/133839984-a00287bf-167c-46c4-871d-934fd5732c0d.png)
![image](https://user-images.githubusercontent.com/69175205/133840089-b94cea29-46d5-4e74-872e-d0cd63c0f0f0.png)

2021-09-17 20:26 UTC, gisellechaumont approved these changes

2021-09-17 23:56 UTC, merged