Issue 7/seccion sucursales
frontendcafe/cmyk-blueberry pull request #26
Opened 2021-09-11 18:01 UTC by celcab27

## Descripcion
-Se creó la sección sucursales
-Se corrigió un error de las rutas en el componente de CardStore
-Se implementó metodología BEM para el css 

## Capturas de pantalla
![image](![sucursales](https://user-images.githubusercontent.com/63078654/132956997-12a16b36-f7c3-4b97-b662-b37dd20fb7e2.png)
![sucursalesmobile](https://user-images.githubusercontent.com/63078654/132957000-028da859-06e7-4cab-90ca-aeea086bc9ae.png)
)

## Issue

https://github.com/frontendcafe/cmyk-blueberry/issues/7

2021-09-11 18:28 UTC, anaggithub commented
Holis! Primero que nada hermoso todo!!  Te dejo algunas correciones para ir trabajando en lo que esperas lo que consultaste con sofi. 

-Guardar todo el contenido de las cards en un archivo data.js, como hicieron los chicos en card mobile
![image](https://user-images.githubusercontent.com/47753872/132957620-d28e0d0d-9d1f-4665-90b9-8d5df925ab97.png)

Luego importarlo en tu index y tomar el texto desde allí. Por favor consultanos si no sabes como hacerlo! :)

Tambén acordate de usar BEM: 
blocke__elemento--modificador

![image](https://user-images.githubusercontent.com/47753872/132957655-3c628cbe-fe19-442c-8762-02976d4529f2.png)

Una idea de las clases como quedarían.. 
.sucursales
.sucursales__title
.sucursales__cards

y en el archivo .scss:

```
.sucursales {
 &--title {
 
 }
  &--cards {
 }
}
```

2021-09-12 17:29 UTC, anaggithub requested changes

2021-09-12 17:29 UTC, anaggithub commented on src/views/sucursales/index.js
> +        <CardStore
Holis! Acá una buena práctica sería hacer un map de lo que te traes desde data. Data es un array, entonces con un map, por cada elemento de ese array, renderizas una cardstore, pasandole las propiedades de ese objeto que está recorriendo con el método map. Si lo hacemos así, si en un futuro se agregaran nuevas cards a ese data.js, las mismas aparecerían solas en el renderizado. Por te las muestra tantos objetos haya en ese array, ya que lo recorre y por cada uno renderiza una card.

Busqué ejemplos en otros repos mios para dejarte uno para que pruebes:
![image](https://user-images.githubusercontent.com/47753872/132996964-b9ccc1e8-e7b1-455d-a58c-9d2919faf086.png)

Si nunca usaste map todavía y querés chismear la docu de mozilla:
https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Array/map

Si te llegas a trabar con esto chiflanos!

2021-09-13 18:52 UTC, Micaela2016 commented
Hola Cel, que lindo toooodo! Lo probé y me aparece esto:
![image](https://user-images.githubusercontent.com/23745160/133139408-2fa7f1d1-f264-4543-9ccb-02931c5f4866.png)

2021-09-13 19:12 UTC, celcab27 commented
> 
> 
> Hola Cel, que lindo toooodo! Lo probé y me aparece esto:
> ![image](https://user-images.githubusercontent.com/23745160/133139408-2fa7f1d1-f264-4543-9ccb-02931c5f4866.png)

Gracias por la observación, Mica!! Ahí le agregué un key a cada card y ya no debería darte ese warning

2021-09-13 22:27 UTC, IgnacioCernich commented
Buenas, estuve viendo y esta re bien todo. Creo que lo unico que habria que cambiar es la imagen de background me parece que tendria que tener un height menor para quedar similar al diseño del figma
![image](https://user-images.githubusercontent.com/81936182/133164494-6bc7767d-cadd-44e5-b6af-ce14aba9c1e3.png)
y la del figma:
![image](https://user-images.githubusercontent.com/81936182/133164543-708095cf-8653-4494-8765-de801430c46a.png)

2021-09-14 00:51 UTC, anaggithub commented on src/App.js
> +      <Sucursales></Sucursales>
Holis! Una ultima cosita! Cuando tenes un componente como acá que no tiene nada dentro simplemente lo podés colocar de esta forma: 
```
 <div className="App">
      <Navbar/>
      <Sucursales/>
 </div>
```


Esto también lo podés hacer donde hiciste el map de CardStore :)

2021-09-14 14:35 UTC, anaggithub requested changes

2021-09-14 14:35 UTC, anaggithub commented on src/components/CardStore/styles.scss
> +.card__container {
Última ultima de verdad jajjaajaj! Acá recorda que este componente lo mergeamos antes de que decidieramos usar bem si mal no recuerdo, entonces le falta acomodarle los estilos usando el ampersand:

Un ej de como hacerlo podes encontrar en el navbar:

![image](https://user-images.githubusercontent.com/47753872/133277668-3ffe9ab1-2366-4857-b6c7-64b38ec91088.png)
![image](https://user-images.githubusercontent.com/47753872/133277726-d3fb3fc9-a600-487a-b6d1-4145291ae3f9.png)

2021-09-14 20:58 UTC, IgnacioCernich approved these changes

2021-09-14 22:56 UTC, nicolashernandezamor-drd commented on src/components/CardStore/index.js
> +    <div className={`card  card--${variant}`}>
Que buena aplicación de BEM con generación dinámica :)

2021-09-14 22:58 UTC, nicolashernandezamor-drd approved these changes

2021-09-15 00:24 UTC, Micaela2016 approved these changes

2021-09-15 01:04 UTC, anaggithub approved these changes

2021-09-15 01:04 UTC, merged