Issue 23/galeria
frontendcafe/cmyk-blueberry pull request #29
Opened 2021-09-12 20:18 UTC by LeoCoronel

## Descripcion
Se realiza galería de imágenes 

## Capturas de pantalla
![image](https://user-images.githubusercontent.com/36435141/133001508-d3620c52-6318-4528-9d92-3ecf816f5dc6.png)
![image](https://user-images.githubusercontent.com/36435141/133001582-85fe5a5b-d7f5-4136-b1e9-2077640cbf7a.png)

## Issue
https://github.com/frontendcafe/cmyk-blueberry/issues/23

2021-09-13 22:57 UTC, gisellechaumont commented
Hola! Me encanto como quedo. Lo único que observo es que la imagen se pone en blanco y negro cuando paso el cursor y el diseño de figma me muestra esto:

Las imagenes se ven asi primero: 
![image](https://user-images.githubusercontent.com/69175205/133167427-bc90765b-ca18-47a3-abd8-488138e002d1.png)
Y cuando paso el cursor se ponen asi: 
![image](https://user-images.githubusercontent.com/69175205/133167503-d154570d-0e8d-4a94-b0ea-f28da30eab6b.png)

2021-09-14 00:55 UTC, anaggithub commented
Holi! Veo que mandaste un commit donde lo quitaste de App.js. Eso por algún motivo? Esta es una sección completa que va en App después de la sección de Información así que sí podríamos ponerla de una en App.js :)

2021-09-14 23:08 UTC, nicolashernandezamor-drd commented on src/components/Gallery/index.js
> +                <img className="gallery__grid__img--6 img--square" src={ IMAGES.viniedo } alt="" />
Esta implementación de BEM no es correcta. Es dificil, porque muchas veces tenemos elementos dentro de elementos. Generalmente, hay dos opciones: o general otro bloque o nombrar los elementos en un sólo nivel.

Creo que para este caso sería adecuado:
- gallery 
- gallery__grid
- gallery__img
- gallery__center-image (no estoy seguro de este caso)

Después, un poco ya opinión:

Podrías utilizar atributos en vez de --1, ..., --5, --6.

`<img grid-area="top-1">`

```scss
img[grid-area] {
   grid-area: top1;
}
```

Es una idea un poco estricta, pero esos modificadores son estructurales y no versiones diferentes del elemento. Es un área gris dentro del framework, así que para discusión.

2021-09-15 00:44 UTC, anaggithub requested changes

2021-09-15 00:44 UTC, anaggithub commented on src/App.js
> +      <Gallery />
Holi! Según veo acá , tu branch está desactualizada porque en este momento ya tenemos el navbar en App y no lo veo. Traten de siempre tener actualizadas sus branchess. :)

2021-09-15 13:52 UTC, anaggithub commented
Holis! Ví que ya actualizaste la branch, ahora salta a la vista que la seccion de sucursales queda como por debajo de galería! Te animás a revisarlo? Me pa q debe ser por le height 100vh de sucursales!
![image](https://user-images.githubusercontent.com/47753872/133446020-5622cc44-dbc2-4daa-8de7-fb4c36604a44.png)

2021-09-15 14:09 UTC, nicolashernandezamor-drd approved these changes

2021-09-15 18:46 UTC, anaggithub approved these changes

2021-09-15 18:47 UTC, merged