Componente mobile creado
frontendcafe/cmyk-blueberry pull request #36
Opened 2021-09-18 00:58 UTC by IgnacioCernich

## Descripcion
Trabaje en el componente mobile al que direcciona el boton de Main que dice "Conocé lo nuevo"

## Capturas de pantalla
![image](https://user-images.githubusercontent.com/81936182/133866781-15a1f0f0-1f96-41ef-a4f9-d1f7170560ab.png)
![image](https://user-images.githubusercontent.com/81936182/133866791-fffe80df-26ee-4ffd-bb73-4dba231221d4.png)
![image](https://user-images.githubusercontent.com/81936182/133866800-597c9ce0-5049-4eec-93a0-50cac7b62949.png)

## Issue
https://github.com/frontendcafe/cmyk-blueberry/issues/24

2021-09-18 02:03 UTC, anaggithub requested changes

2021-09-18 02:03 UTC, anaggithub commented on src/components/CardMainMobile/index.js
> +function CardMainMobile() {
Muy buen trabajo! Está hermoso el componente!! Sí una cosita!! Actualizate esta rama con master (desde la rama, git pull origin master) y ahí te van a llegar los cambios de rutas que trabajó Cel.

Esta card, iría en la ruta /lo-nuevo que ya la tenemos lista!

Si entrás a esa url de la app te va a mostrar esto:

![image](https://user-images.githubusercontent.com/47753872/133868521-c5e713df-18e7-46ae-8969-5943bde4191c.png)


La idea sería que pongas tu componente <CardMainMobile /> ya ahí dentro de esa ruta. Sería acá:
![image](https://user-images.githubusercontent.com/47753872/133868613-ba225203-2c23-4d5e-b018-05e59806ee80.png)

Borrale las lineas comentadas, ese style con margin también, y dentro del div, donde dice "news work", borrá eso y poné tu componente <CardMainMobile /> ahí, así ya la tendremos visible en master!

Luego en otra tarea trabajaremos que en Desktop se renderice la otra card que corresponde a Desktop. Pero de esta forma ya nos quedaría puesta tu card en la app :D

2021-09-18 04:49 UTC, Micaela2016 commented on src/components/CardMainMobile/style.scss
> +      font-weight: bold;
No hace falta poner font-family ya que eso ya esta definido en _base, cambiara font-weight: bold por 700 como dice figma!

2021-09-19 22:11 UTC, Micaela2016 approved these changes

2021-09-19 22:45 UTC, anaggithub approved these changes

2021-09-19 22:45 UTC, merged