Issue 5/seccion informacion
frontendcafe/cmyk-blueberry pull request #45
Opened 2021-09-19 20:56 UTC by LeoCoronel

## Descripcion
Se trabaja en la issue-5 seccion información

## Capturas de pantalla
![image](https://user-images.githubusercontent.com/36435141/133939299-789c9ace-ab85-4dd4-af3e-5b5ad23cd39e.png)
![image](https://user-images.githubusercontent.com/36435141/133942395-2b9438df-4fcd-43bc-bc55-333021708f6a.png)
![image](https://user-images.githubusercontent.com/36435141/133942418-d8b4450b-1aca-46c7-96f1-5d60ee495fc2.png)
![image](https://user-images.githubusercontent.com/36435141/133942433-893ad9ce-1cea-4396-a231-c3d2ad287db6.png)
![image](https://user-images.githubusercontent.com/36435141/133942439-bb8efcbb-8757-4c95-8556-2b81e392b011.png)

## Issue
https://github.com/frontendcafe/cmyk-blueberry/issues/5

2021-09-19 21:38 UTC, anaggithub requested changes

2021-09-19 21:38 UTC, anaggithub commented on src/sections/Information.js
> +import Button from "../components/Button";
Holi!! Hermoso este PR omg me emociono jajajaa. :D

Acá veo que eri había creado una carpeta section... pero nosotros estamos usando la carpeta views para poner las seccioness, te parece mover Información ahí dentro, si no tendríamos dos carpetas con el mismo objetivo..

2021-09-19 21:44 UTC, anaggithub requested changes

2021-09-19 21:44 UTC, anaggithub commented on src/App.js
> +          {moreInfo ? <Sucursales /> : null }
Holi! Luego de tu úultimo commit creo que resolviste medio mal los conflictos porque fijate cómo quedó App ahora:
![image](https://user-images.githubusercontent.com/47753872/133943989-11d3bb9d-3418-47eb-8159-2045199b2c82.png)

De hecho al levantar la branch ni aparece la sección de información, aparece sucursales como estaba antess. Medio rarou. Pero supongo que se va a arreglar cuando corrijas App que quedó medio roto.

2021-09-20 23:29 UTC, Micaela2016 reviewed
Quedo re lindo todooo!!
No recuerdo como era el diseño inicial, pero quizás quedaría mejor en la vista mobile no tener tanto espacio entre main y la sección de información, puede ser porque tiene margin-top: 100px la card
![image](https://user-images.githubusercontent.com/23745160/134089405-d53d10d5-62b6-487b-877f-ede5bdbddab0.png)

2021-09-21 00:02 UTC, celcab27 reviewed
Hola, Leo! Te quedó muy bueno, los únicos detalles que note es que la card azul (cuando están las cards una al lado de la otra) en el figma está un poco más abajo y se nota un poco más la diferencia con respecto a la blanca. Por otro lado, cuando el usuario aprieta el botón de "Más información" este botón debería desaparecer, o al menos no lo veo en el figma en la sección con las cards expandidas.

2021-09-21 18:27 UTC, anaggithub commented
Holis! Otra cosita que noté es que las cards en su versión horizontal ocupan todo el ancho de la pantalla, entonces si vas achicando la pantalla del navegador, en los tamaños que corresponderían a tablet mirá cómo se ve:
![image](https://user-images.githubusercontent.com/47753872/134226831-4f0707db-f1fe-48d7-8be3-097f4c70c317.png)
Te parece agregarle un padding al contenedor, o alguna forma de que no queden así pegadas al borde de la pantalla?

2021-09-21 19:09 UTC, celcab27 approved these changes

2021-09-21 20:08 UTC, Micaela2016 approved these changes

2021-09-22 01:17 UTC, anaggithub approved these changes

2021-09-22 01:17 UTC, merged