Issue 38/card main desktop
frontendcafe/cmyk-blueberry pull request #50
Opened 2021-09-22 02:46 UTC by LeoCoronel

## Descripcion
Se trabaja en la card que aparece al hacer click en el botón "más información" del main en su versión para desktop.

## Capturas de pantalla
![image](https://user-images.githubusercontent.com/36435141/134275346-a0f38809-1ea4-47da-ab92-7cd12aa7320d.png)
![image](https://user-images.githubusercontent.com/36435141/134275365-53f73245-986b-46b4-b5bb-6de0ea9f42cf.png)

## Issue
https://github.com/frontendcafe/cmyk-blueberry/issues/38

2021-09-23 19:51 UTC, Micaela2016 approved these changes
Que buen trabajo Leo! Lo probé y anda perfecto

2021-09-23 23:03 UTC, anaggithub requested changes

2021-09-23 23:03 UTC, anaggithub commented on src/components/CardMainMobile/index.js
> +            <Button variant="secondary" text="Volver" clases='card-container__button'></Button>
Holis! Noté que te falta poner el history push en este botón también!! :D Creo q todo lo demás esta bienn

2021-09-24 14:45 UTC, anaggithub approved these changes

2021-09-24 14:45 UTC, merged