Issue 40/sobre nosotros
frontendcafe/cmyk-blueberry pull request #51
Opened 2021-09-23 02:35 UTC by celcab27

## Descripcion
Se trabajó sobre la sección "About Us" y las cards que se encuentran dentro de las mismas

## Capturas de pantalla
![image](url)

![Captura de pantalla 2021-09-22 a las 23 08 57](https://user-images.githubusercontent.com/63078654/134446830-f4fa902b-c3b7-410a-b120-f76e29feeb7a.png)
![Captura de pantalla 2021-09-22 a las 23 08 52](https://user-images.githubusercontent.com/63078654/134446993-1b33ead0-1cd1-44e6-ba73-fad7f0eb055c.png)
![Captura de pantalla 2021-09-22 a las 23 26 17](https://user-images.githubusercontent.com/63078654/134446847-690a8319-3b57-4a2d-b876-36076a34d3bd.png)
![Captura de pantalla 2021-09-22 a las 23 26 09](https://user-images.githubusercontent.com/63078654/134446840-80dcc370-8360-4c7c-8c5a-b91186c4d8cc.png)

Link al issue trabajado
https://github.com/frontendcafe/cmyk-blueberry/issues/41
https://github.com/frontendcafe/cmyk-blueberry/issues/40

2021-09-23 13:58 UTC, anaggithub requested changes

2021-09-23 13:58 UTC, anaggithub commented on src/views/aboutUS/index.js
> +      </div> : <div className="mainDiv__title"><h2 className="title__content">Sobre nosotros</h2></div>}
Holis! Porfi podés pasar prettier acá está medio desprolijoo.
Genial el renderizado condicional acá! Fijate de eliminar el console.log(). No deberíamos mandar nunca nuestros console.logs que usamos para desarrollar. Por ahí si tenemos un console.log(e) en un try catch es otra cosa, pero este que tenés en línea 12 sí deberíamos sacarlo.

2021-09-23 16:27 UTC, LeoCoronel commented on src/views/aboutUS/index.js
> +        <img src={logo}></img>
A la etiqueta <img /> le falta un alt

2021-09-23 20:00 UTC, Micaela2016 reviewed
Cel te quedo genial, quizás para mobile achicaría un poco el tamaño de los iconos de las redes.
Y un detalle es que en Figma, Sofi no tiene repositorio en Github, sino en Behance:
![image](https://user-images.githubusercontent.com/23745160/134575549-e32a5c3b-217c-4f6e-b87b-759c0983b578.png)

2021-09-28 14:11 UTC, Micaela2016 approved these changes

2021-09-28 19:55 UTC, LeoCoronel commented on src/components/CardAboutUs/index.js
> -        {cards.map((card) =>
Acá faltaban los brackets {}

2021-09-28 20:01 UTC, LeoCoronel commented on src/components/CardAboutUs/index.js
> +                <img src={link.icon} />
Falta un alt a la imagen

2021-09-28 20:09 UTC, LeoCoronel commented
Las cards no son tan altas como las del figma y quedan más cuadradas, podrias cambiar el height. Tambien el borde no son del mismo tamaño y los íconos de linkedin y github uno es más grande que otro

2021-09-29 14:14 UTC, anaggithub approved these changes

2021-09-29 14:19 UTC, merged