Issue-67 se realiza card de la info bodega para el mapa
frontendcafe/cmyk-blueberry pull request #68
Opened 2021-11-29 17:39 UTC by LeoCoronel

## Descripcion
Se trabajo en el issue-67 que es una card para el mapa en versión desktop

## Capturas de pantalla
![image](https://user-images.githubusercontent.com/36435141/143916406-6c5d8577-02ef-469d-b556-c68c67ace6fb.png)

## Issue
[Link al issue trabajado](https://github.com/frontendcafe/cmyk-blueberry/issues/67)

2021-11-30 15:02 UTC, anaggithub requested changes

2021-11-30 15:02 UTC, anaggithub commented on src/components/CardInfoBodega/index.js
> +                <p>(+54 9)1158496231</p>
Un detalle medio bobi pero bueno, fijate que en el figma Sofi le dejó ciertos espacios al número de teléfono :

![image](https://user-images.githubusercontent.com/47753872/144071373-a549569e-495a-46e0-8ae0-6e0b8ccec235.png)

Lo demás lo veo bienn. :D

2021-12-06 20:08 UTC, IgnacioCernich commented
Por lo que veo solo quedaria corregir lo que pidio Hadita

2021-12-07 17:28 UTC, anaggithub approved these changes

2021-12-07 18:02 UTC, IgnacioCernich approved these changes

2021-12-09 15:34 UTC, merged